Improve error messages on compile errors (#239)
Use debug formatting for error messages on compile errors. This provides better error messages that look like this now:

```
error: top level error

Caused by:
    0: error bubbled up once
    1: Root error
```

This PR also removes the JSON blob from the error message as it made the error unreadable.